#170947647 Integrate HoundCI and Add Its Badges
andela/knights-bn-backend pull request #11
Opened 2020-02-05 13:17 UTC by Moise1

#### What does this PR do?
This PR integrates HoundCI and its badge 

#### Description of Task to be completed?
Successfully integrating HoundCI and its badge 

#### How should this be manually tested?
- [clone the repo](https://github.com/andela/knights-bn-backend.git)
- run `npm i` to install the dependencies 
- create a file then start write your code 
- Make a Pull Request then, Hound reviews code in your GitHub pull requests. If Hound finds any issues it will comment inline on your pull request.

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170947647](https://www.pivotaltracker.com/n/projects/2431452)

#### Screenshots (if appropriate)
N/A

2020-02-05 13:40 UTC, Niyonsengaeric requested changes

2020-02-05 13:40 UTC, Niyonsengaeric commented on .hound.yml
> +
new line

2020-02-05 14:45 UTC, T2Wil commented
hey @Moise1 ,
Squash the 2 commits into one commit

2020-02-05 15:39 UTC, EugeneMunya commented
Remember to resolve the conflict

2020-02-06 09:35 UTC, Niyonsengaeric approved these changes

2020-02-06 11:20 UTC, MuhanguziDavid approved these changes
LGTM

2020-02-06 11:20 UTC, merged