ft(one-way-trip): Users should be able to make one-way trip request
andela/knights-bn-backend pull request #42
Opened 2020-02-28 12:45 UTC by Moise1

- create one way trip request
- have a specific manager to  accept/reject the request
- destination cannot be the same as the departure place
- cannot make a similar trip twice (same departure date & destination)

[Start #170947664]

2020-03-03 14:20 UTC, Niyonsengaeric commented
@Moise1  but I don't see the reason why you enter your passportNumber on creating the trip while you have entered it on sign up

2020-03-03 14:28 UTC, Niyonsengaeric commented
<img width="1236" alt="Screen Shot 2020-03-03 at 16 26 38" src="https://user-images.githubusercontent.com/50768983/75785128-e8fd0000-5d6b-11ea-81e4-51d0f523d656.png">

You can also work again on validations, it saves empty spaces

2020-03-03 14:38 UTC, Moise1 commented
@Niyonsengaeric I have applied your feedback.

2020-03-03 14:39 UTC, Niyonsengaeric commented
> @Niyonsengaeric I have applied your feedback.

Cool let me try it again

2020-03-03 14:41 UTC, Niyonsengaeric approved these changes

2020-03-03 15:07 UTC, T2Wil commented
Hey @Moise1 , I think it would be better If we remove some of the non-relevant info for a one_way trip request. I mean returnDate and cities.

![image](https://user-images.githubusercontent.com/30593186/75788605-2adc7500-5d71-11ea-8c8c-7590d4eba195.png)

2020-03-03 15:56 UTC, Moise1 commented
@T2Wil , please check I've applied your feedback.

2020-03-04 07:31 UTC, T2Wil approved these changes

2020-03-04 13:01 UTC, kagabof requested changes

2020-03-04 13:01 UTC, kagabof commented on src/controllers/request.js
> +      const managerId = await models.User.findOne({
You should not use await a then at the same time.

2020-03-04 13:01 UTC, kagabof commented on src/controllers/request.js
> +        const newTripRequest = await models.Request.create({
You should not use await a then at the same time.

2020-03-04 13:01 UTC, kagabof commented on src/middlewares/validateOneWay.js
> +        Error: error.message,
why did you change error to Error?

2020-03-04 13:01 UTC, kagabof commented on src/routes/trips.js
> +} = requestControllers;
@Moise1, I don't understand why initializing new constant variables while you can destructure by the time you are importing.

2020-03-04 13:01 UTC, kagabof commented on src/controllers/request.js
> +      const managerId = await models.User.findOne({
You should also add this in helpers for avoiding code redundancy and for the future use.

2020-03-05 07:53 UTC, kagabof requested changes
Please check your commit message and follow the  https://github.com/andela/engineering-playbook/tree/master/5.%20Developing/Conventions#commit-message

2020-03-05 09:25 UTC, Moise1 commented
@kagabof  please take a look at the commit message. I've applied the feedback.

2020-03-05 10:58 UTC, kagabof approved these changes
Good job.

2020-03-05 10:58 UTC, merged